config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index', only: [:index]
  # É possível escolher quais routes serão criadas
  # resources :manufacturers, only: [:index, :show, :new]
  resources :manufacturers, only: %i[new create edit update destroy]
  resources :subsidiaries
  resources :car_categories, only: %i[index new create edit update destroy]
  resources :car_models, only: %i[new create edit update destroy]
  resources :clients, only: %i[new index create edit update destroy]
  resources :cars
  resources :car_rentals, only: :show

  resources :rentals, only: %i[index show new create destroy] do
    get 'search', on: :collection
    get 'book', on: :member
    post 'book', on: :member, to: 'rentals#create_book'
    get 'cancel', on: :member
    post 'cancel', on: :member, to: 'rentals#cancellation_confirmation'
  end

  namespace :api do
    namespace :v1 do
      resources :cars, only: %i[index show create update]
      resources :rentals, only: %i[create show]
      resources :clients, only: [] do
        get 'rentals', on: :member, to: 'rentals#client_rentals'
      end
    end
  end
end

app/models/subsidiary.rb
class Subsidiary < ApplicationRecord
  has_many :cars, dependent: :nullify

  validates :name, presence: true
  validates :address, presence: true
  validates :cnpj, presence: true, length: { is: 14 },
                   numericality: { only_integer: true }
  validates :zip_code, presence: true, numericality: { only_integer: true },
                       length: { is: 8 }
  validates :number, presence: true, uniqueness: { scope: :zip_code },
                     numericality: { only_integer: true }
  validates :district, presence: true
  validates :state, presence: true, length: { is: 2 }
  validates :city, presence: true

  def full_description
    if name.present? && address.present?
      "#{name}: #{address}"
    else
      I18n.t(:record_invalid, scope:
        %i[activerecord methods subsidiary full_description])
    end
  end
end

app/controllers/subsidiaries_controller.rb
class SubsidiariesController < ApplicationController
  def new
    @subsidiary = Subsidiary.new
  end

  def create
    @subsidiary = Subsidiary.new(subsidiary_params)
    if @subsidiary.save
      flash[:notice] = t('.success')
      redirect_to subsidiaries_path
    else
      render :new
    end
  end

  def index
    @subsidiaries = Subsidiary.all
  end

  def show
    @subsidiary = Subsidiary.find(params[:id])
  end

  def edit
    @subsidiary = Subsidiary.find(params[:id])
  end

  def update
    @subsidiary = Subsidiary.find(params[:id])
    if @subsidiary.update(subsidiary_params)
      flash[:notice] = t('.success')
      redirect_to @subsidiary
    else
      render :edit
    end
  end

  def destroy
    Subsidiary.destroy(params[:id])
    redirect_to subsidiaries_path, notice: t('.success')
  end

  private

  def subsidiary_params
    params.require(:subsidiary).permit(:name, :address, :cnpj, :zip_code,
                                       :number, :district, :state, :city)
  end
end

app/views/subsidiaries/_form.html.erb
<% if @subsidiary.errors.any? %>
  <div class="ls-alert-danger">
    <%= t(:validation_error, scope: [:application_view, :messages]) %>
  </div>
    <ul>
      <% @subsidiary.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
    </ul>
    <br>
<% end %>

<%= form_with(model: @subsidiary, local: true, class: "ls-form-horizontal") do
                                                                     |form| %>
<label class="ls-label col-md-3">
  <%= form.label :name %>
  <p class="ls-label-info">
    <%= t(:name, scope: [:subsidiary_view, :form_label_info]) %>
  </p>
  <%= form.text_field :name %>
</label>

<label class="ls-label col-md-3">
  <%= form.label :cnpj %>
    <p class="ls-label-info">
      <%= t(:cnpj, scope: [:subsidiary_view, :form_label_info]) %>
    </p>
  <%= form.text_field :cnpj %>
</label>

<label class="ls-label col-md-3">
  <%= form.label :address %>
  <p class="ls-label-info">
    <%= t(:address, scope: [:subsidiary_view, :form_label_info]) %>
  </p>
  <%= form.text_field :address %>
</label>

<label class="ls-label col-md-3">
  <%= form.label :number %>
  <p class="ls-label-info">
    <%= t(:number, scope: [:subsidiary_view, :form_label_info]) %>
  </p>
  <%= form.text_field :number %>
</label>

<label class="ls-label col-md-3">
  <%= form.label :district %>
  <p class="ls-label-info">
    <%= t(:district, scope: [:subsidiary_view, :form_label_info]) %>
  </p>
  <%= form.text_field :district %>
</label>

<label class="ls-label col-md-3">
  <%= form.label :zip_code, 'CEP' %>
  <p class="ls-label-info">
    <%= t(:zip_code, scope: [:subsidiary_view, :form_label_info]) %>
  </p>
  <%= form.text_field :zip_code %>
</label>

<label class="ls-label col-md-3">
  <%= form.label :state  %>
  <p class="ls-label-info">
    <%= t(:state, scope: [:subsidiary_view, :form_label_info]) %>
  </p>
  <%= form.text_field :state %>
</label>

<label class="ls-label col-md-3">
  <%= form.label :city %>
  <p class="ls-label-info">
    <%= t(:city, scope: [:subsidiary_view, :form_label_info]) %>
  </p>
  <%= form.text_field :city %>
</label>

<div class="ls-actions-btn">
  <%= form.submit class: 'ls-btn-primary' %>
</div>
<% end %>

app/views/subsidiaries/edit.html.erb
<h1 class="ls-title-intro ls-ico-earth">
  <%= "#{t(:editing_subsidiary,
           scope: [:subsidiary_view, :title])} #{@subsidiary.name}" %>
</h1>

<%= render 'form' %>

app/views/subsidiaries/index.html.erb
<h1 class="ls-title-intro ls-ico-earth">
  <%= Subsidiary.model_name.human(count: 2) %>
</h1>

<% @subsidiaries.each do |subsidiary| %>
<div class="ls-list">
  <header class="ls-list-header">
    <div class="ls-list-title col-md-9">
      <%= link_to subsidiary.name, subsidiary_path(subsidiary) %>
      <small>
        <%= "#{subsidiary.address}, #{subsidiary.number}, "\
            "#{subsidiary.district}, #{subsidiary.state} - "\
            "#{subsidiary.city} — #{subsidiary.zip_code}" %>
      </small>
    </div>
    <div class="col-md-3 ls-txt-right" id="subsidiary-<%= subsidiary.id %>">
      <%= link_to t(:edit, scope: [:application_view, :buttons]),
                    edit_subsidiary_path(subsidiary), class: "ls-btn" %>
      <%= link_to t(:delete, scope: [:application_view, :buttons]),
                    subsidiary, class: "ls-btn-primary-danger ls-ico-remove",
                    method: :delete, data: {confirm: "#{t(:confirm?,
                       scope: [:application_view, :messages])}"} %>
    </div>
  </header>
  <div class="ls-list-content ">
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Subsidiary.human_attribute_name('cnpj') %>
      </span>
      <strong><%= subsidiary.cnpj %></strong>
    </div>
  </div>
</div>
<br>
<% end %>

<br>

<%= link_to t(:new_register, scope: [:subsidiary_view, :buttons]),
              new_subsidiary_path, class: 'ls-btn-primary' %>

<br>
<br>

app/views/subsidiaries/new.html.erb
<h1 class="ls-title-intro ls-ico-home">
  <%= "#{t(:new_subsidiary,
           scope: [:subsidiary_view, :title])} #{@subsidiary.name}" %>
</h1>

<%= render 'form' %>

app/views/subsidiaries/show.html.erb
<h1 class="ls-title-intro ls-ico-earth">
  <%= Subsidiary.model_name.human %>
</h1>

<div class="ls-list">
  <header class="ls-list-header">
    <div class="ls-list-title col-md-9">
        <a href="#" ><%= "#{@subsidiary.name}" %></a>
    </div>
  </header>
  <div class="ls-list-content ">
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Subsidiary.human_attribute_name('cnpj') %>
      </span>
      <strong><%= @subsidiary.cnpj %></strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Subsidiary.human_attribute_name('address') %>
      </span>
      <strong><%= @subsidiary.address %></strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Subsidiary.human_attribute_name('number') %>
      </span>
      <strong><%= @subsidiary.number %></strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Subsidiary.human_attribute_name('district') %>
      </span>
      <strong><%= @subsidiary.district %></strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Subsidiary.human_attribute_name('state') %>
      </span>
      <strong><%= @subsidiary.state %></strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Subsidiary.human_attribute_name('city') %>
      </span>
      <strong><%= @subsidiary.city %></strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Subsidiary.human_attribute_name('zip_code') %>
      </span>
      <strong><%= @subsidiary.zip_code %></strong>
    </div>
  </div>
</div>

<div id="cars" class="ls-tab-content ls-active">
  <table class="ls-table ls-table-striped ls-bg-header">
    <thead>
      <tr>
        <th><%= Car.human_attribute_name('license_plate') %></th>
        <th class="hidden-xs"><%= Manufacturer.model_name.human %></th>
        <th><%= CarModel.model_name.human %></th>
        <th class="hidden-xs"><%= Subsidiary.model_name.human %></th>
      </tr>
    </thead>
    <tbody>
      <% @subsidiary.cars.each do |car| %>
      <tr>
        <td><%= link_to car.license_plate, car_path(car) %></td>
        <td class="hidden-xs"><%= car.car_model.manufacturer.name %></td>
        <td><%= car.car_model.name %></td>
        <td class="hidden-xs"><%= car.subsidiary.name %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>