config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index', only: [:index]
  # É possível escolher quais routes serão criadas
  # resources :manufacturers, only: [:index, :show, :new]
  resources :manufacturers, only: %i[new create edit update destroy]
  resources :subsidiaries
  resources :car_categories, only: %i[index new create edit update destroy]
  resources :car_models, only: %i[new create edit update destroy]
  resources :clients, only: %i[new index create edit update destroy]
  resources :cars
  resources :car_rentals, only: :show

  resources :rentals, only: %i[index show new create destroy] do
    get 'search', on: :collection
    get 'book', on: :member
    post 'book', on: :member, to: 'rentals#create_book'
    get 'cancel', on: :member
    post 'cancel', on: :member, to: 'rentals#cancellation_confirmation'
  end

  namespace :api do
    namespace :v1 do
      resources :cars, only: %i[index show create update]
      resources :rentals, only: %i[create show]
      resources :clients, only: [] do
        get 'rentals', on: :member, to: 'rentals#client_rentals'
      end
    end
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :client
  belongs_to :car_category
  belongs_to :user
  has_one :car_rental, dependent: :restrict_with_exception

  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :valid_start_date, :valid_end_date
  validate :availables_cars, on: %i[create save]

  enum status: { scheduled: 0, in_progress: 1, expired: 2, canceled: 3 }

  def able_to_cancel?
    Time.zone.today < (start_date - 1.day)
  end

  def daily_price_total
    if car_category.present?
      car_category.daily_rate + car_category.car_insurance +
        car_category.third_party_insurance
    else
      I18n.t(:incomplete_rental, scope:
        %i[activerecord methods rental daily_price_total])
    end
  end

  def car_insurance
    if car_category.present?
      car_category.car_insurance
    else
      I18n.t(:incomplete_rental, scope:
        %i[activerecord methods rental daily_price_total])
    end
  end

  def third_party_insurance
    if car_category.present?
      car_category.third_party_insurance
    else
      I18n.t(:incomplete_rental, scope:
        %i[activerecord methods rental daily_price_total])
    end
  end

  def rental_expired?
    if start_date < Time.zone.today && scheduled?
      errors.add(:base, I18n.t(:expired_rental, scope:
        %i[activerecord methods rental expired?]))
      true
    else
      false
    end
  end

  private

  def valid_start_date
    return unless start_date && start_date < Time.zone.today

    message = I18n.t(:invalid_start_date, scope:
                %i[activerecord methods rental valid_start_date])
    errors.add(:start_date, message)
  end

  def valid_end_date
    return unless end_date && end_date < start_date

    message = I18n.t(:invalid_end_date, scope:
                %i[activerecord methods rental valid_end_date])
    errors.add(:end_date, message)
  end

  def availables_cars
    if car_category && car_category.car_models.present?
      message = I18n.t(:no_car, scope:
                  %i[activerecord methods rental availables_cars])
      errors[:base] << message if rented_cars.length >= category_cars.length
    else
      I18n.t(:incomplete_rental, scope:
        %i[activerecord methods rental availables_cars])
    end
  end

  def rented_cars
    car_category_rentals.where(start_date: start_date..end_date)
                        .or(car_category_rentals
                        .where(end_date: start_date..end_date))
                        .or(start_date_before_and_end_date_after)
  end

  def car_category_rentals
    scheduled = 0
    in_progress = 1
    Rental.where(car_category: car_category, status: scheduled..in_progress)
  end

  def category_cars
    Car.where(car_model: car_category.car_models)
  end

  def start_date_before_and_end_date_after
    car_category_rentals.where('start_date < ? AND end_date > ?',
                               start_date.to_s, end_date.to_s)
  end
end

app/controllers/api/v1/rentals_controller.rb
class Api::V1::RentalsController < Api::V1::ApiController
  def create
    @rental = Rental.new(rental_params)
    render json: @rental, status: :ok if @rental.save!
  rescue ActiveRecord::RecordInvalid
    render json: @rental.errors.full_messages, status: :precondition_failed
  end

  def client_rentals
    @client = Client.find_by!(document: params[:id])
    @rentals = Rental.where(client: @client)
    unless @rentals.empty?
      return render json: @rentals.as_json(include: { client:
        { only: %i[name document] }, car_category: { only: :name } }, except:
        %i[client_id car_category_id]), status: :ok
    end
    render json: '', status: :no_content
  rescue ActiveRecord::RecordNotFound
    render json: '', status: :not_found
  end

  def show
    @rental = Rental.find(params[:id])
    render json: @rental.as_json(include: { client:
      { only: %i[name document] }, car_category: { only: :name } }, except:
      %i[client_id car_category_id]), status: :ok
  rescue ActiveRecord::RecordNotFound
    render json: '', status: :not_found
  end

  private

  def rental_params
    params.permit(:code, :start_date, :end_date, :client_id, :car_category_id,
                  :user_id)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :clients_collection, :categories_collection, only: %i[new edit]

  def new
    @rental = Rental.new
  end

  def create
    @rental = Rental.new(params_rental)
    @rental.code = SecureRandom.hex(5)
    @rental.user = current_user

    return redirect_to @rental, notice: t('.success') if @rental.save

    clients_collection
    categories_collection
    render :new
  end

  def index
    @rentals = Rental.order(status: :asc)
  end

  def show
    @rental = Rental.find(params[:id])
    if @rental.scheduled? && @rental.rental_expired?
      flash.now[:alert] = t('.expired')
      @rental.expired!
      @valid = false
    else
      @valid = true
    end
  end

  def search
    # Busca exata
    # @rentals = Rental.where(code: params[:q])
    # Outro modo de busca exata, agora, utilizando SQL
    # @rentals = Rental.where("code LIKE ?", "#{params[:q]}")
    @q = params[:q]
    @rentals = Rental.where('code LIKE ?', "%#{params[:q]}%")
  end

  def book
    @rental = Rental.find(params[:id])
    @car_rental = CarRental.new
    @cars = Car.where(car_model: @rental.car_category.car_models)
  end

  def create_book
    @rental = Rental.find(params[:id])
    @car = Car.find(params[:car_rental][:car_id])
    @car_rental = CarRental.new(car_rental_parameters)
    redirect_to @car_rental, notice: t('.success') if @car_rental.save!
  end

  def cancel
    @rental = Rental.find(params[:id])
    unless @rental.able_to_cancel?
      return redirect_to @rental, alert: I18n.t(:cannot_cancel, scope:
        %i[activerecord methods cancel_rental])
    end
    @cancel_rental = CancelRental.new
  end

  def cancellation_confirmation
    @rental = Rental.find(params[:id])
    @cancel_rental = CancelRental.new(rental: @rental,
                                      reason: params[:cancel_rental][:reason])
    if @cancel_rental.save
      flash[:notice] = t('.success')
      redirect_to rentals_path
    else
      render :cancel
    end
  end

  private

  def car_rental_parameters
    {
      car: @car, rental: @rental, daily_price: @rental.daily_price_total,
      car_insurance: @rental.car_insurance, start_mileage: @car.mileage,
      third_party_insurance: @rental.third_party_insurance,
      end_mileage: @car.mileage
    }
  end

  def clients_collection
    @clients = Client.all
  end

  def categories_collection
    @car_categories = CarCategory.all
  end

  def params_rental
    params.require(:rental).permit(:start_date, :end_date, :client_id,
                                   :car_category_id)
  end
end

app/views/rentals/_form.html.erb
<% if @rental.errors.any? %>
  <div class="ls-alert-danger">
    <%= t(:validation_error, scope: [:application_view, :messages]) %>
  </div>
  <ul>
    <% @rental.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<br>

<%= form_with(model: @rental, local: true, class: "ls-form-horizontal") do
                                                                 |form| %>
<label class="ls-label col-md-3">
    <%= form.label :start_date %>
      <p class="ls-label-info"></p>
        <%= form.text_field :start_date, class: "datepicker",
                            id: "datepickerExample",
                            placeholder: "dd/mm/aaaa" %>
</label>

<label class="ls-label col-md-3">
  <%= form.label :end_date %>
    <p class="ls-label-info"></p>
  <%= form.text_field :end_date, class: "datepicker",
                      id: "datepickerExample",
                      placeholder: "dd/mm/aaaa" %>
</label>

<label class="ls-label col-md-3">
  <%= form.label :client_id %>
  <p class="ls-label-info"></p>
  <div class="ls-custom-select">
   <%= form.collection_select :client_id, @clients, :id,
                             :name_document, class: "ls-custom" %>
  </div>
</label>

<label class="ls-label col-md-3">
  <%= form.label :car_category_id %>
  <p class="ls-label-info"></p>
  <div class="ls-custom-select">
   <%= form.collection_select :car_category_id, @car_categories, :id,
                              :name, class: "ls-custom" %>
  </div>
</label>

<div class="ls-actions-btn">
  <%= form.submit class: 'ls-btn-primary' %>
</div>

<% end %>

app/views/rentals/_full_results.html.erb
<div class="ls-list">
  <header class="ls-list-header">
    <div class="ls-list-title col-md-9">
      <h2><%= @rental.code %></h2>
    </div>
    <div class="col-md-3 ls-txt-right" id=<%= "rental-#{@rental.id}" %>>
      <% if @valid && @rental.scheduled? %>
      <%= link_to t(:effectuate, scope: [:rental_view, :buttons]),
                     book_rental_path(@rental), class: "ls-btn" %>
      <% end %>
      <% if !@rental.canceled? && @rental.scheduled? %>
        <%= link_to t(:cancel, scope: [:application_view, :buttons]),
                      cancel_rental_path(@rental),
                      class: "ls-btn-primary-danger" %>
      <% end %>
    </div>
  </header>
  <div class="ls-list-content ">
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Rental.human_attribute_name('client') %>
      </span>
      <strong><%= @rental.client.name %></strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= User.model_name.human %>
      </span>
      <strong><%= @rental.user.email %></strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Rental.human_attribute_name('car_category') %>
      </span>
      <strong><%= @rental.car_category.name %></strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Rental.human_attribute_name('start_date') %>
      </span>
      <strong><%= @rental.start_date.strftime("%d/%m/%Y") if @rental %></strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Client.human_attribute_name('email') %>
      </span>
      <strong><%= @rental.client.email %></strong>
    </div>
    <div class="col-xs-12 col-md-6">
      <span class="ls-list-label">
        <%= Rental.human_attribute_name('end_date') %>
      </span>
      <strong>
        <%= @rental.end_date.strftime("%d/%m/%Y") if @rental %>
      </strong>
    </div>
  </div>
</div>

app/views/rentals/_partial_results.html.erb
<div id="cars" class="ls-tab-content ls-active">
  <table class="ls-table ls-table-striped ls-bg-header">
    <thead>
      <tr>
        <th>
          <%= t(:code, scope: [:activerecord, :attributes, :rental]) %>
        </th>
        <th class="hidden-xs">
          <%= t(:client, scope: [:activerecord, :attributes, :rental]) %>
        </th>
        <th>
          <%= t(:email, scope: [:activerecord, :attributes, :client]) %>
        </th>
        <th class="hidden-xs">
          <%= t(:car_category, scope: [:activerecord, :attributes, :rental]) %>
        </th>
        <th>
          <%= t(:status, scope: [:rental_view, :title]) %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @rentals.each do |rental| %>
      <tr>
        <td><%= link_to rental.code, rental_path(rental) %></td>
        <td class="hidden-xs"><%= rental.client.name %></td>
        <td><%= rental.client.email %></td>
        <td class="hidden-xs"><%= rental.car_category.name %></td>
        <td>
          <% rental.expired? %>
          <%= t(rental.status, scope: [:activerecord, :attributes, :rental, :status]) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rentals/_search.html.erb
<div class="ls-box-filter">
<%= form_tag search_rentals_path, method: :get,
             class: "ls-form ls-form-inline" do %>
<%= label_tag :q, t(:search, scope: [:rental_view, :form_labels]) %>
<%= text_field_tag :q %>
<%= submit_tag t(:seek, scope: [:rental_view, :buttons]), class: "ls-btn" %>
<% end %>
</div>

app/views/rentals/book.html.erb
<h1 class="ls-title-intro ls-ico-week">
  <%= t(:effectuate_rental, scope: [:rental_view, :title])%>
</h1>

<br>

<% if @cars.any? %>
<%= form_for @car_rental, url: book_rental_path, class: "ls-form row" do |f| %>

<label class="ls-label col-md-4">
<%= f.label :car_id, t(:car_id, scope: [:rental_view, :form_labels]) %>
<p class="ls-label-info"></p>
<div class="ls-custom-select">
<%= f.collection_select :car_id, @cars, :id, :full_description,
                        class: "ls-custom" %>
</div>
</label>
<div class="ls-actions-btn">
  <%= f.submit t(:conclude, scope: [:rental_view, :buttons]),
      class: 'ls-btn-primary' %>
</div>

<% end %>


<% else %>
<p> <%= t(:no_car, scope: [:rental_view, :messages]) %> </p>

<% end %>

app/views/rentals/cancel.html.erb
<h1 class="ls-title-intro ls-ico-week">
  <%= "#{Rental.model_name.human} ##{@rental.code}" %>
</h1>

<% if @cancel_rental.errors.any? %>
  <div class="ls-alert-danger">
    <%= t(:validation_error, scope: [:application_view, :messages]) %>
  </div>
  <ul>
    <% @cancel_rental.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<br>

<%= form_with(model: @cancel_rental, url: cancel_rental_path, local: true,
              class: "ls-form-horizontal", method: :post) do |form| %>

<label class="ls-label col-md-9">
    <%= form.label :reason, CancelRental.human_attribute_name('reason') %>
      <p class="ls-label-info"></p>
        <%= form.text_area :reason, size: '100x10' %>
</label>

<div class="ls-actions-btn">
  <%= form.submit t(:cancellation, scope: [:rental_view, :buttons]),
                   class: 'ls-btn-primary' %>
</div>

<% end %>

app/views/rentals/index.html.erb
<h1 class="ls-title-intro ls-ico-week">
  <%= Rental.model_name.human(count: 2) %>
</h1>

<%= render partial: 'search' %>

<%= render partial: 'partial_results' %>

<br>

<%= link_to t(:schedule, scope: [:rental_view, :buttons]),
            new_rental_path, class: 'ls-btn-primary' %>

app/views/rentals/new.html.erb
<h1 class="ls-title-intro ls-ico-week">
  <%= t(:new_subsidiary, scope: [:rental_view, :title]) %>
</h1>

<%= render partial: 'form' %>

app/views/rentals/search.html.erb
<h1 class="ls-title-intro ls-ico-week">
<%= Rental.model_name.human(count: 2) %>
</h1>

<%= render partial: 'search' %>

<% if @q.present? %>

<div id="cars" class="ls-tab-content ls-active">
  <table class="ls-table ls-table-striped ls-bg-header">
    <thead>
      <tr>
        <th>
          <%= t(:code, scope: [:activerecord, :attributes, :rental]) %>
        </th>
        <th class="hidden-xs">
          <%= t(:client, scope: [:activerecord, :attributes, :rental]) %>
        </th>
        <th>
          <%= t(:email, scope: [:activerecord, :attributes, :client]) %>
        </th>
        <th class="hidden-xs">
          <%= t(:car_category, scope: [:activerecord, :attributes, :rental]) %>
        </th>
        <th>
          <%= t(:status, scope: [:rental_view, :title]) %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @rentals.each do |rental| %>
      <tr>
        <td><%= link_to rental.code, rental_path(rental) %></td>
        <td class="hidden-xs"><%= rental.client.name %></td>
        <td><%= rental.client.email %></td>
        <td class="hidden-xs"><%= rental.car_category.name %></td>
        <td>
          <% rental.expired? %>
          <%= t(rental.status, scope: [:activerecord, :attributes, :rental, :status]) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= "#{@rentals.length} #{t(:results_found,
                            scope: [:application_view, :messages])}" %>

<% end %>

app/views/rentals/show.html.erb
<h1 class="ls-title-intro ls-ico-week">
  <%= "#{Rental.model_name.human} ##{@rental.code}" %>
</h1>

<%= render partial: 'full_results.html.erb' %>