config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index', only: [:index]
  # É possível escolher quais routes serão criadas
  # resources :manufacturers, only: [:index, :show, :new]
  resources :manufacturers, only: %i[new create edit update destroy]
  resources :subsidiaries
  resources :car_categories, only: %i[index new create edit update destroy]
  resources :car_models, only: %i[new create edit update destroy]
  resources :clients, only: %i[new index create edit update destroy]
  resources :cars
  resources :car_rentals, only: :show

  resources :rentals, only: %i[index show new create destroy] do
    get 'search', on: :collection
    get 'book', on: :member
    post 'book', on: :member, to: 'rentals#create_book'
    get 'cancel', on: :member
    post 'cancel', on: :member, to: 'rentals#cancellation_confirmation'
  end

  namespace :api do
    namespace :v1 do
      resources :cars, only: %i[index show create update]
      resources :rentals, only: %i[create show]
      resources :clients, only: [] do
        get 'rentals', on: :member, to: 'rentals#client_rentals'
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="ls-theme-wine">
<head>
  <title><%= t(:brand, scope: [:application_view]) %></title>


  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!-- Se tirar essa chamada, para de funcionar chamadas delete para os métodos -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- end -->

  <meta charset="utf-8">
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <meta name="description" content="Insira aqui a descrição da página.">
  <link href="http://assets.locaweb.com.br/locastyle/3.10.1/stylesheets/locastyle.css" rel="stylesheet" type="text/css">
  <link rel="icon" sizes="192x192" href="/locawebstyle/assets/images/ico-boilerplate.png">
  <link rel="apple-touch-icon" href="/locawebstyle/assets/images/ico-boilerplate.png">
</head>
<body>
  <% if user_signed_in? %>
  <div class="ls-topbar ">

    <!-- Barra de Notificações -->
    <div class="ls-notification-topbar">

      <!-- Links de apoio -->
      <!-- <div class="ls-alerts-list">
      <a href="#" class="ls-ico-bell-o" data-counter="8" data-ls-module="topbarCurtain" data-target="#ls-notification-curtain"><span>Notificações</span></a>
      <a href="#" class="ls-ico-bullhorn" data-ls-module="topbarCurtain" data-target="#ls-help-curtain"><span>Ajuda</span></a>
      <a href="#" class="ls-ico-question" data-ls-module="topbarCurtain" data-target="#ls-feedback-curtain"><span>Sugestões</span></a>
    </div> -->

    <!-- Dropdown com detalhes da conta de usuário -->
    <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
      <a href="" class="ls-ico-user">
        <!-- <img src="/locawebstyle/assets/images/locastyle/avatar-example.jpg" alt="" /> -->
        <span class="ls-name"><%= current_user.email %></span>

      </a>

      <nav class="ls-dropdown-nav ls-user-menu">
        <ul>
          <li id="logout"><%= link_to t(:logout, scope: [:application_view, :topbar]), destroy_user_session_path, method: :delete %></li>
          <!-- <li><a href="#">Faturas</a></li>
          <li><a href="#">Planos</a></li>
          <li><a href="#">Sair</a></li> -->
        </ul>
      </nav>
    </div>
  </div>

<span class="ls-show-sidebar ls-ico-menu"></span>

<a href="/"  class="ls-go-next">
  <span class="ls-text">
    <%= t(:back_to_list_of_services, scope: [:application_view, :topbar]) %>
  </span>
</a>

<!-- Nome do produto/marca com sidebar -->
<h1 class="ls-brand-name">
  <a href="/" class="ls-ico-earth">
    <small><%= t(:rental_cars, scope: [:application_view]) %></small>
    <%= t(:brand, scope: [:application_view]) %>
  </a>
</h1>

<!-- Nome do produto/marca sem sidebar quando for o pre-painel  -->
</div>


<aside class="ls-sidebar">

  <div class="ls-sidebar-inner">

    <nav class="ls-menu">
      <ul>
        <li><%= link_to t(:home_page, scope: :menu), root_path %></li>
        <li><%= link_to Subsidiary.model_name.human(count: 2), subsidiaries_path %></li>
        <li><%= link_to Car.model_name.human(count: 2), cars_path %></li>
        <li><%= link_to Client.model_name.human(count: 2), clients_path %></li>
        <li><%= link_to CarCategory.model_name.human(count: 2), car_categories_path %></li>
        <li><%= link_to Rental.model_name.human(count: 2), rentals_path %></li>

        <!-- Menu com submenu -->
        <!-- <li>
        <a href="#" class="ls-ico-cog" title="Configurações">Configurações</a>
        <ul>
        <li><a href="/locawebstyle/documentacao/exemplos/painel1/config-domain">Domínios da Revenda</a></li>
        <li><a href="/locawebstyle/documentacao/exemplos/painel1/config-email">E-mail de Remetente</a></li>
        <li><a href="/locawebstyle/documentacao/exemplos/painel1/config-aspect">Aparência</a></li>
        <li><a href="/locawebstyle/documentacao/exemplos/painel1/config-answer">Atendimento</a></li>
        <li><a href="/locawebstyle/documentacao/exemplos/painel1/config-api">Chave de acesso para API</a></li>
      </ul>
    </li> -->
  </ul>
</nav>


</div>
</aside>



<main class="ls-main ">
  <div class="container-fluid">
    <p></p>
    <p class="ls-alert-danger"><%= alert %></p>
    <p class="ls-alert-success"><%= notice %></p>
    <% end %>
    <%= yield %>
  </div>
</main>




    <!-- <aside class="ls-notification">
      <nav class="ls-notification-list" id="ls-notification-curtain" style="left: 1716px;">
        <h3 class="ls-title-2">Notificações</h3>
        <ul>
          <li class="ls-dismissable">
            <a href="#">Blanditiis est est dolorem iure voluptatem eos deleniti repellat et laborum consequatur</a>
            <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
          </li>
          <li class="ls-dismissable">
            <a href="#">Similique eos rerum perferendis voluptatibus</a>
            <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
          </li>
          <li class="ls-dismissable">
            <a href="#">Qui numquam iusto suscipit nisi qui unde</a>
            <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
          </li>
          <li class="ls-dismissable">
            <a href="#">Nisi aut assumenda dignissimos qui ea in deserunt quo deleniti dolorum quo et consequatur</a>
            <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
          </li>
          <li class="ls-dismissable">
            <a href="#">Sunt consequuntur aut aut a molestiae veritatis assumenda voluptas nam placeat eius ad</a>
            <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
          </li>
        </ul>
      </nav> -->

      <!-- <nav class="ls-notification-list" id="ls-help-curtain" style="left: 1756px;">
        <h3 class="ls-title-2">Feedback</h3>
        <ul>
          <li><a href="#">&gt; quo fugiat facilis nulla perspiciatis consequatur</a></li>
          <li><a href="#">&gt; enim et labore repellat enim debitis</a></li>
        </ul>
      </nav>

      <nav class="ls-notification-list" id="ls-feedback-curtain" style="left: 1796px;">
        <h3 class="ls-title-2">Ajuda</h3>
        <ul>
          <li class="ls-txt-center hidden-xs">
            <a href="#" class="ls-btn-dark ls-btn-tour">Fazer um Tour</a>
          </li>
          <li><a href="#">&gt; Guia</a></li>
          <li><a href="#">&gt; Wiki</a></li>
        </ul>
      </nav>
    </aside> -->

    <!-- We recommended use jQuery 1.10 or up -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="http://assets.locaweb.com.br/locastyle/3.10.1/javascripts/locastyle.js" type="text/javascript"></script>

  </body>
</html>